import  turtle
turtle.speed(10)
turtle.up()
turtle.goto(-200,200)
turtle.begin_fill()
turtle.fillcolor("red")
turtle.pencolor("red")
for i in range(2):
    turtle.forward(438)
    turtle.right(90)
    turtle.forward(292)
    turtle.right(90)
turtle.end_fill()
turtle.fillcolor("yellow")
turtle.pencolor("yellow")
turtle.up()
turtle.goto(-170,145)
turtle.down()
turtle.begin_fill()
for x in range(5):
    turtle.forward(50)
    turtle.right(144)
turtle.end_fill()
turtle.up()
turtle.goto(-100,180)
turtle.setheading(305)
turtle.down()
turtle.begin_fill()
for i in range (5):
    turtle.forward(20)
    turtle.right(144)
turtle.end_fill()
turtle.up()
turtle.goto(-85,150)
turtle.setheading(30)
turtle.down()
turtle.begin_fill()
for i in range (5):
    turtle.forward(20)
    turtle.right(144)
turtle.end_fill()
turtle.up()
turtle.goto(-85,120)
turtle.setheading(3)
turtle.down()
turtle.begin_fill()
for i in range (5):
    turtle.forward(20)
    turtle.right(144)
turtle.end_fill()
turtle.up()
turtle.goto(-100,100)
turtle.setheading(300)
turtle.begin_fill()
for i in range (5):
    turtle.forward(20)
    turtle.right(144)
turtle.end_fill()
turtle.hideturtle()
turtle.down()
